version: "3.8"

services:
  html-to-image:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_TOKEN=DaduBhogLagaRaheHai
      - HOST_IMAGES=1
      - ROOT_PATH=/html_to_image
      - MAX_DOWNLOADS=5
      - IMAGE_EXPIRY_DAYS=3
      - BASE_URL=https://tools.automationtester.in
    volumes:
      - ./app/static:/app/static
    restart: unless-stopped
